name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ryanarcel/critary
          IMAGE_TAG: latest
        run: |
          # Build image with no cache to guarantee updated drivers
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2 via AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying updated container and running migrations" \
            --parameters 'commands=[
              "aws ecr get-login-password --region '${{ env.AWS_REGION }}' | docker login --username AWS --password-stdin '${{ steps.login-ecr.outputs.registry }}'",
              "docker stop critari || true",
              "docker rm critari || true",
              "docker rmi '${{ steps.login-ecr.outputs.registry }}/ryanarcel/critary:latest' || true",
              "docker pull '${{ steps.login-ecr.outputs.registry }}/ryanarcel/critary:latest'",
              "docker run -d --name critari -p 80:80 --env-file /home/ec2-user/.env --restart always '${{ steps.login-ecr.outputs.registry }}/ryanarcel/critary:latest'",
              "docker exec critari php artisan config:clear",
              "docker exec critari php artisan config:cache",
              "docker exec critari php artisan migrate --force"
            ]' \
            --region ${{ env.AWS_REGION }}